### PR TITLE
Add Theme command to change themes

### PR DESCRIPTION
**Pull request by ChrysanthemumT**
change theme with theme -bg dark/light

### CODE REVIEW

**Comment by ChrysanthemumT** [comment]
https://github.com/AY2324S2-CS2103T-W11-3/tp/assets/88710694/ba5c0987-520c-4589-bb47-10029b9a93e0

**Comment by gauravuj** [comment]
looks really cool! thank you for creating the command for changing theme - it's a life saver!

btw would you be fine if I change few things for the light theme or are you gonna work on it further?

**Comment by ChrysanthemumT** [comment]
go ahead

**Comment by gauravuj** [comment]
oh wow! that's a nice setup - makes it so much easier to add more themes

**Pull request merged**
